import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import Head from "next/head";

export default function Home() {
  const [input, setInput] = useState("");

  const { data, isLoading, isError, refetch, error } = useQuery<{
    list: string[];
    error?: string;
  }>({
    queryKey: ["recipes"],
    queryFn: async () => {
      const response = await fetch(`/api/recipe?items=${input}`);
      if (!response.ok) {
        throw new Error(response.statusText);
      }
      return response.json();
    },
    enabled: false,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form
          className="mb-[10vh] mt-[15vh] flex gap-4"
          onSubmit={async (e) => {
            e.preventDefault();
            await refetch();
          }}
        >
          <input
            className="border-blue-gray-200 text-blue-gray-700 placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200 disabled:bg-blue-gray-50 peer h-full w-full rounded-[7px] border bg-transparent px-3 py-2.5 font-sans text-sm font-normal text-white outline outline-0 transition-all placeholder-shown:border focus:border-2 focus:border-pink-500 focus:border-t-transparent focus:outline-0 disabled:border-0"
            onChange={(e) => setInput(e.target.value)}
          />
          <button
            className="rounded-lg bg-pink-500 px-6 py-3 font-sans text-xs font-bold uppercase text-white shadow-md shadow-pink-500/20 transition-all hover:shadow-lg hover:shadow-pink-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
            disabled={isLoading}
          >
            Search
          </button>
        </form>

        {isLoading && (
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-solid border-white border-t-transparent" />
        )}

        {data && (
          <ul className="overflow-hidden rounded border border-gray-200 shadow-md">
            {data.list?.map((item, i) => (
              <li
                key={i}
                className="border-b border-gray-200 bg-white px-4 py-2 transition-all duration-300 ease-in-out last:border-none hover:bg-sky-100 hover:text-sky-900"
              >
                {item}
              </li>
            ))}
          </ul>
        )}

        {isError && (
          <p className="border-b border-gray-200 bg-white px-4 py-2 transition-all duration-300 ease-in-out last:border-none hover:bg-sky-100 hover:text-sky-900">
            {error.message}
          </p>
        )}
      </main>
    </>
  );
}
